apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: static-ingress
 namespace: royal
spec:
 rules:
 - host: royal.lekkalahyma.xyz
   http:
     paths:
     - path:
       backend:
         serviceName: static-svc
         servicePort: 80